# Form implementation generated from reading ui file 'new_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_window(object):
    def setupUi(self, new_window):
        new_window.setObjectName("new_window")
        new_window.resize(533, 307)
        self.name = QtWidgets.QLabel(parent=new_window)
        self.name.setGeometry(QtCore.QRect(80, 30, 371, 31))
        self.name.setStyleSheet("background: grey;\n"
"color: white;")
        self.name.setObjectName("name")

        self.retranslateUi(new_window)
        QtCore.QMetaObject.connectSlotsByName(new_window)

    def retranslateUi(self, new_window):
        _translate = QtCore.QCoreApplication.translate
        new_window.setWindowTitle(_translate("new_window", "Новое окно"))
        self.name.setText(_translate("new_window", "ФИО"))
