# Form implementation generated from reading ui file 'reg_win.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_reg_win(object):
    def setupUi(self, reg_win):
        reg_win.setObjectName("reg_win")
        reg_win.resize(500, 400)
        reg_win.setMinimumSize(QtCore.QSize(500, 400))
        reg_win.setMaximumSize(QtCore.QSize(500, 400))
        reg_win.setStyleSheet("background: rgb(255, 255, 255);")
        self.login_line = QtWidgets.QLineEdit(parent=reg_win)
        self.login_line.setGeometry(QtCore.QRect(120, 30, 250, 40))
        self.login_line.setStyleSheet("")
        self.login_line.setObjectName("login_line")
        self.pass_line = QtWidgets.QLineEdit(parent=reg_win)
        self.pass_line.setGeometry(QtCore.QRect(120, 100, 250, 40))
        self.pass_line.setStyleSheet("")
        self.pass_line.setObjectName("pass_line")
        self.bd_line = QtWidgets.QLineEdit(parent=reg_win)
        self.bd_line.setGeometry(QtCore.QRect(120, 170, 250, 40))
        self.bd_line.setStyleSheet("placeholder: Дата рождения;\n"
"color: black;\n"
"")
        self.bd_line.setObjectName("bd_line")
        self.sale_line = QtWidgets.QLineEdit(parent=reg_win)
        self.sale_line.setGeometry(QtCore.QRect(120, 240, 250, 40))
        self.sale_line.setStyleSheet("placeholder: Скидка;\n"
"color")
        self.sale_line.setObjectName("sale_line")
        self.button = QtWidgets.QPushButton(parent=reg_win)
        self.button.setGeometry(QtCore.QRect(150, 300, 191, 41))
        self.button.setStyleSheet("background: rgb(157, 205, 231);\n"
"")
        self.button.setObjectName("button")

        self.retranslateUi(reg_win)
        QtCore.QMetaObject.connectSlotsByName(reg_win)

    def retranslateUi(self, reg_win):
        _translate = QtCore.QCoreApplication.translate
        reg_win.setWindowTitle(_translate("reg_win", "Окно регистрации"))
        self.button.setText(_translate("reg_win", "Зарегестрироваться"))
